foreach(feature IN ITEMS
    GGML_SSE42 GGML_AVX GGML_AVX2 GGML_FMA GGML_F16C GGML_BMI2
    GGML_LLAMAFILE GGML_OPENMP GGML_CPU_REPACK)
    set(${feature} ON CACHE BOOL "")
endforeach()

foreach(feature IN ITEMS
    GGML_NATIVE GGML_AVX512 GGML_AVX512_VBMI GGML_AVX512_VNNI
    GGML_AVX512_BF16 GGML_AVX_VNNI GGML_AMX_TILE GGML_AMX_INT8
    GGML_AMX_BF16 GGML_BLAS GGML_CUDA)
    set(${feature} OFF CACHE BOOL "")
endforeach()
