set(CMAKE_OSX_ARCHITECTURES "x86_64" CACHE STRING "")
set(CMAKE_OSX_DEPLOYMENT_TARGET "11.0" CACHE STRING "")

foreach(feature IN ITEMS GGML_METAL GGML_METAL_EMBED_LIBRARY GGML_ACCELERATE)
    set(${feature} ON CACHE BOOL "")
endforeach()

foreach(feature IN ITEMS
    GGML_NATIVE GGML_BLAS GGML_OPENMP GGML_LLAMAFILE
    GGML_SSE42 GGML_AVX GGML_AVX2 GGML_AVX_VNNI
    GGML_AVX512 GGML_AVX512_VBMI GGML_AVX512_VNNI GGML_AVX512_BF16
    GGML_FMA GGML_F16C GGML_BMI2
    GGML_AMX_TILE GGML_AMX_INT8 GGML_AMX_BF16)
    set(${feature} OFF CACHE BOOL "")
endforeach()
