set(CMAKE_OSX_ARCHITECTURES "arm64" CACHE STRING "")
set(CMAKE_OSX_DEPLOYMENT_TARGET "14.0" CACHE STRING "")
set(GGML_BLAS_VENDOR "Apple" CACHE STRING "")

foreach(feature IN ITEMS
    GGML_METAL GGML_METAL_EMBED_LIBRARY GGML_ACCELERATE GGML_BLAS)
    set(${feature} ON CACHE BOOL "")
endforeach()

foreach(feature IN ITEMS
    GGML_NATIVE GGML_OPENMP GGML_RPC GGML_CCACHE LLAMA_OPENSSL)
    set(${feature} OFF CACHE BOOL "")
endforeach()
