set(CMAKE_OSX_ARCHITECTURES "arm64" CACHE STRING "")
set(CMAKE_OSX_DEPLOYMENT_TARGET "11.0" CACHE STRING "")

foreach(feature IN ITEMS
    GGML_METAL GGML_METAL_EMBED_LIBRARY GGML_ACCELERATE)
    set(${feature} ON CACHE BOOL "")
endforeach()

foreach(feature IN ITEMS
    GGML_BLAS GGML_NATIVE GGML_OPENMP GGML_RPC GGML_CCACHE LLAMA_OPENSSL)
    set(${feature} OFF CACHE BOOL "")
endforeach()
