set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreadedDLL" CACHE STRING "")
set(GGML_NATIVE OFF CACHE BOOL "")
set(GGML_AVX2 ON CACHE BOOL "")
set(GGML_AVX512 OFF CACHE BOOL "")
set(GGML_AVX_VNNI OFF CACHE BOOL "")
set(GGML_CUDA OFF CACHE BOOL "")
set(GGML_BLAS OFF CACHE BOOL "")
set(GGML_OPENMP ON CACHE BOOL "")

set(CMAKE_PROJECT_llama_cpp_INCLUDE
    "${CMAKE_CURRENT_LIST_DIR}/windows-runtime.cmake" CACHE FILEPATH "")
